#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-shared
Version  : 1.0
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-transfer/0.9.0/maven-artifact-transfer-0.9.0.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-transfer/0.9.0/maven-artifact-transfer-0.9.0.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-transfer/0.9.1/maven-artifact-transfer-0.9.1.jar
Source5  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-artifact-transfer/0.9.1/maven-artifact-transfer-0.9.1.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
Source7  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.0/maven-common-artifact-filters-3.0.0.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar
Source10  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-analyzer/1.10/maven-dependency-analyzer-1.10.jar
Source12  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-analyzer/1.10/maven-dependency-analyzer-1.10.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
Source14  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
Source16  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.pom
Source17  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
Source18  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.pom
Source19  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.jar
Source20  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.pom
Source21  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar
Source22  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom
Source23  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar
Source24  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.pom
Source25  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom
Source26  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom
Source27  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom
Source28  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom
Source29  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom
Source30  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/20/maven-shared-components-20.pom
Source31  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom
Source32  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/22/maven-shared-components-22.pom
Source33  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/3/maven-shared-components-3.pom
Source34  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/30/maven-shared-components-30.pom
Source35  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/31/maven-shared-components-31.pom
Source36  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-components/9/maven-shared-components-9.pom
Source37  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar
Source38  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom
Source39  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.jar
Source40  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.pom
Source41  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-resources/2/maven-shared-resources-2.jar
Source42  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-resources/2/maven-shared-resources-2.pom
Source43  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom
Source44  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.3/maven-shared-utils-0.3.pom
Source45  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.jar
Source46  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.pom
Source47  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.jar
Source48  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.pom
Source49  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
Source50  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.pom
Source51  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.1/maven-shared-utils-3.0.1.pom
Source52  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar
Source53  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.pom
Source54  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.jar
Source55  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.pom
Source56  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
Source57  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-shared-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-shared package.
Group: Data

%description data
data components for the mvn-maven-shared package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/12
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/15
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/17
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/17

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/18
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/18

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/19
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/19

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/20
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/20

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/21
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/21

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/22
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/22

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/3
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/30
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/30

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/31
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/31

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/9
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.1
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.3
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.1
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-resolver/1.0/maven-artifact-resolver-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0/maven-artifact-transfer-0.9.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.0/maven-artifact-transfer-0.9.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1/maven-artifact-transfer-0.9.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.9.1/maven-artifact-transfer-0.9.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.0/maven-common-artifact-filters-3.0.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10/maven-dependency-analyzer-1.10.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.10/maven-dependency-analyzer-1.10.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/20/maven-shared-components-20.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/22/maven-shared-components-22.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/3/maven-shared-components-3.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/30/maven-shared-components-30.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/31/maven-shared-components-31.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-components/9/maven-shared-components-9.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2/maven-shared-resources-2.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-resources/2/maven-shared-resources-2.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.3/maven-shared-utils-0.3.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.1/maven-shared-utils-3.0.1.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.pom
